services:
  server:
    image: bigbang1112/mania-server-manager:alpine
    restart: unless-stopped
    environment:
      MSM_SERVER_TYPE: TMF
      MSM_SERVER_IDENTIFIER: my-tmf-xaseco-server
      MSM_ACCOUNT_LOGIN: your_login
      MSM_ACCOUNT_PASSWORD: your_password
      MSM_MATCH_SETTINGS: tracklist.txt # XASECO expects tracklist.txt by default. With evoesports/xaseco, you should also change 'autosave_matchsettings' in 'rasp.settings.php' to this file name.
      MSM_MATCH_SETTINGS_BASE: NadeoTimeAttack.txt
      MSM_SERVER_NAME: My ManiaServerManager Server
      MSM_CFG_SERVER_MAX_PLAYERS: 255
      MSM_CFG_CONFIG_XMLRPC_ALLOW_REMOTE: xaseco
      MSM_CFG_CONFIG_PACKMASK: united
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "3450:3450/udp"
    volumes:
      - ./servers:/app/data/servers
      - msm_archives:/app/data/archives

  xaseco:
    image: evoesports/xaseco
    restart: unless-stopped
    #depends_on:
    #  server:
    #    condition: service_healthy
    #    restart: true
    environment:
      XASECO_TMSERVER_LOGIN: SuperAdmin
      XASECO_TMSERVER_PASSWORD: SuperAdmin
      XASECO_TMSERVER_IP: server
      XASECO_TMSERVER_PORT: 5000
      XASECO_MYSQL_SERVER: mariadb
      XASECO_MYSQL_LOGIN: xaseco
      XASECO_MYSQL_PASSWORD: your_xaseco_password
      XASECO_MYSQL_DATABASE: xaseco
      XASECO_DEDIMANIA_LOGIN: your_login
      XASECO_DEDIMANIA_PASSWORD: your_password
      XASECO_DEDIMANIA_NATION: OTH # remember to set this to the actual country
      XASECO_MASTERADMINS: login1,login2,login3
    volumes:
      - ./controllers/my-tmf-xaseco-server:/xaseco
      - ./servers/my-tmf-xaseco-server/GameData:/app/data/servers/my-tmf-xaseco-server/GameData
    networks:
      - default
      - db_mariadb

networks:
  db_mariadb:
    external: true

volumes:
  msm_archives:
