services:
  server:
    image: bigbang1112/mania-server-manager:alpine
    restart: unless-stopped
    environment:
      MSM_SERVER_TYPE: TMF
      MSM_ACCOUNT_LOGIN: your_login
      MSM_ACCOUNT_PASSWORD: your_password
      MSM_MATCH_SETTINGS: Nations/NationsWhite.txt
      MSM_SERVER_NAME: My ManiaServerManager Server
      MSM_CFG_SERVER_MAX_PLAYERS: 255
      MSM_CFG_CONFIG_XMLRPC_ALLOW_REMOTE: xaseco
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "3450:3450/udp"
    volumes:
      - ./my-tmf-xaseco-server:/app/data/versions/TMF_Latest
      - msm-archives:/app/data/archives

  xaseco:
    image: evoesports/xaseco
    restart: unless-stopped
    environment:
      XASECO_TMSERVER_LOGIN: SuperAdmin
      XASECO_TMSERVER_PASSWORD: SuperAdmin
      XASECO_TMSERVER_IP: server
      XASECO_TMSERVER_PORT: 5000
      XASECO_MYSQL_SERVER: mariadb
      XASECO_MYSQL_LOGIN: xaseco
      XASECO_MYSQL_PASSWORD: your_xaseco_password
      XASECO_MYSQL_DATABASE: xaseco
      XASECO_DEDIMANIA_LOGIN: your_login
      XASECO_DEDIMANIA_PASSWORD: your_password
      XASECO_DEDIMANIA_NATION: OTH # remember to set this to the actual country
      XASECO_MASTERADMINS: login1,login2,login3
    volumes:
      #- "xaseco:/xaseco"
      - ./my-tmf-xaseco-server/GameData:/server/GameData
    networks:
      - default
      - db_mariadb

networks:
  db_mariadb:
    external: true
